import React, { useState, useEffect } from 'react';
import { Loader, card, formfield } from '../components';


const Home = () => {

  
  const [loading, setLoading] = useState(true);
  const [allPosts, setAllPosts] = useState(null);


  return (
    <section className="max-w-w7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className="mt-16">
        <formfield/>
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className="flex justify-centre items-centre">
            <Loader/>
          </div>
        ):(
          <>

          </>
        )}
      </div>

    </section>
  )
}

export default home